create table employees_history (
       history_id     number generated by default as identity primary key,
       employee_id    number not null,
       first_name     varchar2(20),
       last_name      varchar2(25),
       job_id         varchar2(10),
       department_id  number,
       salary         number,
       hire_date      date,
       fire_date      date default sysdate not null,
       fired_by       varchar2(100 char) default user,
       fire_reason    varchar2(200 char)
       
);
